name: Get all go versions

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

jobs:
  update_symbol_list:
    name: Retrieve all Go versions every day
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Update database
        run: |
          scrapy runspider golang_versions/spiders/versions.py -O data/versions.json
          git config user.name golang-versions-bot
          git add .
          git commit -m "[bot] Update versions database"
          git push origin main
